AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'Gemfile'
    - '**/*.rb'
  Exclude:
    - 'app/assets/stylesheets/Unify/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'public/assets/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
